name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, main for bugfix and other changes), we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到正确的分支 (新特性发到 feature 分支，其他发到 main 分支) ，我们会尽快进行 Review，提前感谢和期待您的贡献。
            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

      # - name: invalid
      #   if: github.event.label.name == 'invalid'
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'create-comment,close-issue'
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Template](https://github.com/walinejs/waline/issues/new/choose) to create an issue, thank you!
      #       你好 @${{ github.event.issue.user.login }}，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 模板](https://github.com/walinejs/waline/issues/new/choose) 来创建 issue 以方便我们定位错误。谢谢配合！
